packages:
  - "cakes-api"
  - "cakes-ui"
catalog:
  "@eslint/js": "^9.18.0"
  "@types/express": "^5.0.0"
  "@types/react": "^19.0.8"
  "@types/react-dom": "^19.0.3"
  "@vite-pwa/assets-generator": "^0.2.6"
  "@vitejs/plugin-react": "^4.2.1"
  "concurrently": "^8.2.2"
  "dotenv": "^16.4.7"
  "eslint": "^9.18.0"
  "eslint-plugin-react-hooks": "^5.0.0"
  "eslint-plugin-react-refresh": "^0.4.18"
  "express": "^4.21.2"
  "globals": "^15.14.0"
  "nodemon": "^3.1.9"
  "prettier": "^3.5.2"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "typescript": "~5.7.2"
  "tsx": "^4.19.3"
  "typescript-eslint": "^8.20.0"
  "vite": "^6.0.11"
  "vite-plugin-pwa": "^0.21.1"
  "workbox-core": "^7.3.0"
  "workbox-window": "^7.3.0"
