packages:
  - "cakes-api"
  - "cakes-ui"
catalog:
  "@eslint/js": "^9.18.0"
  "@hookform/resolvers": "^4.1.2"
  "@prisma/client": "^6.4.1"
  "@radix-ui/react-label": "^2.1.2"
  "@radix-ui/react-slot": "^1.1.2"
  "@tailwindcss/vite": "^4.0.9"
  "@tanstack/react-query": "^5.66.11"
  "@tanstack/eslint-plugin-query": "^5.66.1"
  "@types/compression": "^1.7.5"
  "@types/cors": "^2.8.17"
  "@types/express": "^5.0.0"
  "@types/node": "^22.13.8"
  "@types/react": "^19.0.8"
  "@types/react-dom": "^19.0.3"
  "@vite-pwa/assets-generator": "^0.2.6"
  "@vitejs/plugin-react": "^4.2.1"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "compression": "^1.8.0"
  "concurrently": "^8.2.2"
  "cors": "^2.8.5"
  "dotenv": "^16.4.7"
  "eslint": "^9.18.0"
  "eslint-plugin-react-hooks": "^5.0.0"
  "eslint-plugin-react-refresh": "^0.4.18"
  "express": "^4.21.2"
  "globals": "^15.14.0"
  "helmet": "^8.0.0"
  "lucide-react": "^0.477.0"
  "nodemon": "^3.1.9"
  "prettier": "^3.5.2"
  "prisma": "^6.4.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "react-hook-form": "^7.54.2"
  "react-router": "^7.2.0"
  "tailwind-merge": "^3.0.2"
  "tailwindcss": "^4.0.9"
  "tailwindcss-animate": "^1.0.7"
  "typescript": "~5.7.2"
  "tsx": "^4.19.3"
  "typescript-eslint": "^8.20.0"
  "vite": "^6.0.11"
  "vite-plugin-pwa": "^0.21.1"
  "winston": "^3.17.0"
  "workbox-core": "^7.3.0"
  "workbox-window": "^7.3.0"
  "zod": "^3.24.2"