---
name: cakes
services:
  database:
    image: postgres:16-bookworm
    restart: unless-stopped
    shm_size: 1g
    command: postgres -c 'max_connections=200'
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

